// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.lec.proto;

public interface StudentRepListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lec.proto.StudentRepList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  java.util.List<StudentRep>
      getStudentRepList();
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  StudentRep getStudentRep(int index);
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  int getStudentRepCount();
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  java.util.List<? extends StudentRepOrBuilder>
      getStudentRepOrBuilderList();
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  StudentRepOrBuilder getStudentRepOrBuilder(
          int index);
}
