// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.lec.proto;

/**
 * Protobuf type {@code com.lec.proto.StudentRepList}
 */
public  final class StudentRepList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lec.proto.StudentRepList)
    StudentRepListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentRepList.newBuilder() to construct.
  private StudentRepList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentRepList() {
    studentRep_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentRepList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              studentRep_ = new java.util.ArrayList<StudentRep>();
              mutable_bitField0_ |= 0x00000001;
            }
            studentRep_.add(
                input.readMessage(StudentRep.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        studentRep_ = java.util.Collections.unmodifiableList(studentRep_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return StudentProto.internal_static_com_lec_proto_StudentRepList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return StudentProto.internal_static_com_lec_proto_StudentRepList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StudentRepList.class, Builder.class);
  }

  public static final int STUDENTREP_FIELD_NUMBER = 1;
  private java.util.List<StudentRep> studentRep_;
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  public java.util.List<StudentRep> getStudentRepList() {
    return studentRep_;
  }
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  public java.util.List<? extends StudentRepOrBuilder>
      getStudentRepOrBuilderList() {
    return studentRep_;
  }
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  public int getStudentRepCount() {
    return studentRep_.size();
  }
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  public StudentRep getStudentRep(int index) {
    return studentRep_.get(index);
  }
  /**
   * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
   */
  public StudentRepOrBuilder getStudentRepOrBuilder(
      int index) {
    return studentRep_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < studentRep_.size(); i++) {
      output.writeMessage(1, studentRep_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < studentRep_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, studentRep_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StudentRepList)) {
      return super.equals(obj);
    }
    StudentRepList other = (StudentRepList) obj;

    if (!getStudentRepList()
        .equals(other.getStudentRepList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentRepCount() > 0) {
      hash = (37 * hash) + STUDENTREP_FIELD_NUMBER;
      hash = (53 * hash) + getStudentRepList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StudentRepList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentRepList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentRepList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentRepList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentRepList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentRepList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentRepList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StudentRepList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StudentRepList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StudentRepList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StudentRepList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StudentRepList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StudentRepList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.lec.proto.StudentRepList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lec.proto.StudentRepList)
      StudentRepListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentProto.internal_static_com_lec_proto_StudentRepList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentProto.internal_static_com_lec_proto_StudentRepList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StudentRepList.class, Builder.class);
    }

    // Construct using com.lec.proto.StudentRepList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentRepFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (studentRepBuilder_ == null) {
        studentRep_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentRepBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return StudentProto.internal_static_com_lec_proto_StudentRepList_descriptor;
    }

    @Override
    public StudentRepList getDefaultInstanceForType() {
      return StudentRepList.getDefaultInstance();
    }

    @Override
    public StudentRepList build() {
      StudentRepList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StudentRepList buildPartial() {
      StudentRepList result = new StudentRepList(this);
      int from_bitField0_ = bitField0_;
      if (studentRepBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          studentRep_ = java.util.Collections.unmodifiableList(studentRep_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.studentRep_ = studentRep_;
      } else {
        result.studentRep_ = studentRepBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StudentRepList) {
        return mergeFrom((StudentRepList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StudentRepList other) {
      if (other == StudentRepList.getDefaultInstance()) return this;
      if (studentRepBuilder_ == null) {
        if (!other.studentRep_.isEmpty()) {
          if (studentRep_.isEmpty()) {
            studentRep_ = other.studentRep_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentRepIsMutable();
            studentRep_.addAll(other.studentRep_);
          }
          onChanged();
        }
      } else {
        if (!other.studentRep_.isEmpty()) {
          if (studentRepBuilder_.isEmpty()) {
            studentRepBuilder_.dispose();
            studentRepBuilder_ = null;
            studentRep_ = other.studentRep_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentRepBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentRepFieldBuilder() : null;
          } else {
            studentRepBuilder_.addAllMessages(other.studentRep_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StudentRepList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StudentRepList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<StudentRep> studentRep_ =
      java.util.Collections.emptyList();
    private void ensureStudentRepIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        studentRep_ = new java.util.ArrayList<StudentRep>(studentRep_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        StudentRep, StudentRep.Builder, StudentRepOrBuilder> studentRepBuilder_;

    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public java.util.List<StudentRep> getStudentRepList() {
      if (studentRepBuilder_ == null) {
        return java.util.Collections.unmodifiableList(studentRep_);
      } else {
        return studentRepBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public int getStudentRepCount() {
      if (studentRepBuilder_ == null) {
        return studentRep_.size();
      } else {
        return studentRepBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public StudentRep getStudentRep(int index) {
      if (studentRepBuilder_ == null) {
        return studentRep_.get(index);
      } else {
        return studentRepBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder setStudentRep(
        int index, StudentRep value) {
      if (studentRepBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRepIsMutable();
        studentRep_.set(index, value);
        onChanged();
      } else {
        studentRepBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder setStudentRep(
        int index, StudentRep.Builder builderForValue) {
      if (studentRepBuilder_ == null) {
        ensureStudentRepIsMutable();
        studentRep_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentRepBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder addStudentRep(StudentRep value) {
      if (studentRepBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRepIsMutable();
        studentRep_.add(value);
        onChanged();
      } else {
        studentRepBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder addStudentRep(
        int index, StudentRep value) {
      if (studentRepBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRepIsMutable();
        studentRep_.add(index, value);
        onChanged();
      } else {
        studentRepBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder addStudentRep(
        StudentRep.Builder builderForValue) {
      if (studentRepBuilder_ == null) {
        ensureStudentRepIsMutable();
        studentRep_.add(builderForValue.build());
        onChanged();
      } else {
        studentRepBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder addStudentRep(
        int index, StudentRep.Builder builderForValue) {
      if (studentRepBuilder_ == null) {
        ensureStudentRepIsMutable();
        studentRep_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentRepBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder addAllStudentRep(
        Iterable<? extends StudentRep> values) {
      if (studentRepBuilder_ == null) {
        ensureStudentRepIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, studentRep_);
        onChanged();
      } else {
        studentRepBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder clearStudentRep() {
      if (studentRepBuilder_ == null) {
        studentRep_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentRepBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public Builder removeStudentRep(int index) {
      if (studentRepBuilder_ == null) {
        ensureStudentRepIsMutable();
        studentRep_.remove(index);
        onChanged();
      } else {
        studentRepBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public StudentRep.Builder getStudentRepBuilder(
        int index) {
      return getStudentRepFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public StudentRepOrBuilder getStudentRepOrBuilder(
        int index) {
      if (studentRepBuilder_ == null) {
        return studentRep_.get(index);  } else {
        return studentRepBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public java.util.List<? extends StudentRepOrBuilder>
         getStudentRepOrBuilderList() {
      if (studentRepBuilder_ != null) {
        return studentRepBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(studentRep_);
      }
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public StudentRep.Builder addStudentRepBuilder() {
      return getStudentRepFieldBuilder().addBuilder(
          StudentRep.getDefaultInstance());
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public StudentRep.Builder addStudentRepBuilder(
        int index) {
      return getStudentRepFieldBuilder().addBuilder(
          index, StudentRep.getDefaultInstance());
    }
    /**
     * <code>repeated .com.lec.proto.StudentRep studentRep = 1;</code>
     */
    public java.util.List<StudentRep.Builder>
         getStudentRepBuilderList() {
      return getStudentRepFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        StudentRep, StudentRep.Builder, StudentRepOrBuilder>
        getStudentRepFieldBuilder() {
      if (studentRepBuilder_ == null) {
        studentRepBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            StudentRep, StudentRep.Builder, StudentRepOrBuilder>(
                studentRep_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        studentRep_ = null;
      }
      return studentRepBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lec.proto.StudentRepList)
  }

  // @@protoc_insertion_point(class_scope:com.lec.proto.StudentRepList)
  private static final StudentRepList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StudentRepList();
  }

  public static StudentRepList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentRepList>
      PARSER = new com.google.protobuf.AbstractParser<StudentRepList>() {
    @Override
    public StudentRepList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentRepList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentRepList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StudentRepList> getParserForType() {
    return PARSER;
  }

  @Override
  public StudentRepList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

