// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.lec.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lec_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lec_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lec_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lec_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lec_proto_StudentReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lec_proto_StudentReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lec_proto_StudentRep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lec_proto_StudentRep_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\rcom.lec.proto\"\035\n\tMyRequ" +
      "est\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010r" +
      "ealname\030\002 \001(\t\"\031\n\nStudentReq\022\013\n\003age\030\001 \001(\005" +
      "\"5\n\nStudentRep\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(" +
      "\005\022\014\n\004city\030\003 \001(\t2\255\001\n\016StudentService\022N\n\025Ge" +
      "tRealNameByUsername\022\030.com.lec.proto.MyRe" +
      "quest\032\031.com.lec.proto.MyResponse\"\000\022K\n\017Ge" +
      "tStudentByAge\022\031.com.lec.proto.StudentReq" +
      "\032\031.com.lec.proto.StudentRep\"\0000\001B\037\n\rcom.l" +
      "ec.protoB\014StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lec_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lec_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lec_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_lec_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lec_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lec_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_lec_proto_StudentReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lec_proto_StudentReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lec_proto_StudentReq_descriptor,
        new String[] { "Age", });
    internal_static_com_lec_proto_StudentRep_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_lec_proto_StudentRep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lec_proto_StudentRep_descriptor,
        new String[] { "Name", "Age", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
